### ISSUE TITLE
WTF liberapay icon on the right side ?

### ISSUE THREAD

**Issue by XavCC** [XavCC/xavcc.github.io#30]
Just trying, as a noob, to stick [ Liberapay Widget](https://github.com/XavCC/xavcc.github.io/tree/master/_layouts) to right but *fail* 

Please help me with learning by doing if you want.

**Comment by FrancoisDupayrat** [comment]
You mean like this or something else?
![liberapay float right](https://user-images.githubusercontent.com/1129774/34692945-398c6d4a-f4c2-11e7-9069-f3ce22b5ee43.PNG)

Should be easy if it's only that, it's only a float:right; to add in the same css. I guess the <right> on the liberapay button is a failed try too?

**Comment by XavCC** [comment]
Your rock !
