### ISSUE TITLE
Commande non-équilibrée

### ISSUE THREAD

**Issue by Seb35** [XavCC/xavcc.github.io#74]
Hello, dans le [billet Hyperboria](https://xavcc.github.io/sciences/2018/03/12/hyperboria.html), la commande pour générer des mots de passe n’est pas équilibrée au niveau des apostrophes : dans la commande `tr` en particulier : ça ouvre une apostrophe simple sans la refermer, ça ouvre un guillemet sans le refermer, et les backticks ` sont censés représenter une sous-commande en shell, ce qui semble bizarre dans le contexte).

Je ne sais pas où tu l’as trouvée, mais certains caractères ont dû sauter lors de la copie, peut-être des guillemets tout autour et avec des échappements à l’intérieur ?). J’ai modifié un peu en la commande suivante qui fonctionne, mais peut-être pas optimale par rapport à une expression plus recherchée.

    cat /dev/urandom | strings | head -n 20 | tr -d "' \n\"\t {\}" | head -c 40 && echo

Pour info sinon, /dev/urandom donne de la qualité moindre (dans les propriétés de génération de l’aléa) que [/dev/random](https://fr.wikipedia.org/wiki//dev/random). Le problème de ce dernier est qu’il est très lent car il n’y souvent pas assez d’entropie dans un ordinateur ; pour contrecarer ce problème, il est possible d’installer haveged (paquet Debian du même nom) qui va générer de l’entropie complémentaire pour /dev/random -- en plus ça semble être de la [technologie rennaise](http://www.irisa.fr/caps/projects/hipsor/).

**Comment by XavCC** [comment]
Merci @Seb35 

c'est une commande rédigée maison avec la fatigue du hackathon et mal retranscrite dans le billet. Je corrige ! 

Acceptes-tu que j eplace en quote dans le billet ton "pour info" ? Cela me semble très utile pour la suite.

**Comment by Seb35** [comment]
Merci pour la correction et bien sûr pour le post-scriptum.
